api = "0.4"

[buildpack]
id = "sgudz/minecraft"
version = "0.2.4"
name = "Minecraft"
homepage = "https://github.com/sgudz/mcrdocker"
description = "Create a Minecraft server for a Docker container"
keywords = ["minecraft", "game"]

[[buildpack.licenses]]
type = "MIT"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.4.0"
    optional = true

  [[order.group]]
    id = "heroku/jvm"
    version = "0.1.0"

  [[order.group]]
    id = "jkutner/raspberry-juice"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "jkutner/minecraft-server"
    version = "0.1.4"
